
name: Auto build demo.sh

on:
  push:
    paths:
      - "demo/demo.patch.sh"
      - "monobash"

jobs:
  build-demo:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set git identity
        run: |
          git config user.name "CIbot"
          git config user.email "miniyu157@163.com"

      - name: Build demo.sh
        run: |
          cd demo
          ./build-demo.sh

      - name: Check if demo.sh changed
        id: diff
        run: |
          if git diff --quiet demo/demo.sh; then
            echo "changed=false" >> $GITHUB_OUTPUT
          else
            echo "changed=true" >> $GITHUB_OUTPUT
          fi

      - name: Commit demo.sh
        if: steps.diff.outputs.changed == 'true'
        run: |
          git add demo/demo.sh
          git commit -m "auto: ⚙️ regenerate demo.sh"

      - name: Push
        if: steps.diff.outputs.changed == 'true'
        run: |
          git push
